nameOverride: "prometheus"
namespaceOverride: "monitoring"
prometheus:
  prometheusSpec:
    storageSpec:
      image:
        registry: quay.io
        repository: prometheus/prometheus
        tag: v3.7.2
        sha: ""
        pullPolicy: IfNotPresent
      volumeClaimTemplate:
        spec:
          storageClassName: gluster
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi