nameOverride: "prometheus"
namespaceOverride: "monitoring"
prometheus:
  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v3.7.1
      sha: ""
      pullPolicy: IfNotPresent
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gluster
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi